#!/usr/bin/env python3
"""
gen_c22_exhaustive_slices.py
============================

Generate deterministic Class-22 NL=4 slices.

This script enumerates the 2^16 distinct NL=4 slices obtained by projecting
the 40-dimensional Class-22 self-equivalence subspace V22 onto the 200 fixed
coordinates p <= 4. Each generated slice has 24 free coefficients.

Place this file in:
    E:\apn-gb-search\src\gen_c22_exhaustive_slices.py

Run from repo root:
    python src\gen_c22_exhaustive_slices.py --start 0 --count 20

Then run Magma from batch:
    cd batch
    powershell -ExecutionPolicy Bypass -File ..\magma_templates\run_batch.ps1 -Pattern "apn_c22_all_*.m"

Notes:
  * This does NOT use random seeds.
  * It covers the Class-22 NL=4 quotient systematically.
  * Total slices should be 2^16 = 65536.
"""

import argparse
import json
import time
from pathlib import Path

import gen_batch as gb


def vec_to_int(v):
    z = 0
    for i, b in enumerate(v):
        if b & 1:
            z |= (1 << i)
    return z


def gf2_rank_and_basis_columns(columns_as_int):
    """
    Return rank and indices of independent columns over GF(2).
    Columns are represented as Python integers.
    """
    basis = {}       # pivot_bit -> vector
    basis_col_idx = []

    for idx, x0 in enumerate(columns_as_int):
        x = x0
        while x:
            p = x.bit_length() - 1
            if p in basis:
                x ^= basis[p]
            else:
                basis[p] = x
                basis_col_idx.append(idx)
                break

    return len(basis), basis_col_idx


def coeffs_from_v22_params(params):
    """
    params: list of len len(gb.fc22), free coordinates of V22.
    returns: full 224-bit coefficient vector satisfying F∘A22 = A22∘F.
    """
    if len(params) != len(gb.fc22):
        raise ValueError(f"Expected {len(gb.fc22)} params, got {len(params)}")

    coeffs = [0] * gb.nvars

    for bit, f in zip(params, gb.fc22):
        coeffs[f] = int(bit) & 1

    for p, deps in gb.sol22.items():
        val = 0
        for f, c in deps.items():
            if c & 1:
                val ^= coeffs[f]
        coeffs[p] = val & 1

    return coeffs


def fixed_signature_bits(coeffs):
    return [coeffs[i] for i in gb.C22_FIXED_VARS]


def build_projection_basis():
    """
    Build a basis of the image of the projection:
        V22 -> fixed coordinates p<=4.
    """
    cols = []
    for i in range(len(gb.fc22)):
        params = [0] * len(gb.fc22)
        params[i] = 1
        coeffs = coeffs_from_v22_params(params)
        sig = fixed_signature_bits(coeffs)
        cols.append(vec_to_int(sig))

    rank, basis_param_indices = gf2_rank_and_basis_columns(cols)
    return rank, basis_param_indices


def coeffs_for_slice_index(slice_index, basis_param_indices):
    """
    Construct one representative point in V22 whose fixed-coordinate signature
    corresponds to slice_index in the chosen projection basis.
    """
    params = [0] * len(gb.fc22)

    for t, param_idx in enumerate(basis_param_indices):
        params[param_idx] = (slice_index >> t) & 1

    return coeffs_from_v22_params(params)


def patch_magma_text(text):
    """
    Ensure Magma writes results into batch/results/.
    """
    text = text.replace(
        'Results -> apn_results_',
        'Results -> results/apn_results_'
    )
    text = text.replace(
        'results_file := "apn_results_',
        'results_file := "results/apn_results_'
    )
    text = text.replace(
        "auto-generated by gen_batch.py",
        "auto-generated by gen_c22_exhaustive_slices.py"
    )
    return text


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--start", type=int, default=0,
                    help="First slice index, 0 <= start < 65536")
    ap.add_argument("--count", type=int, default=20,
                    help="Number of slices to generate")
    ap.add_argument("--out", type=Path, default=None,
                    help="Output batch directory; default is repo_root/batch")
    ap.add_argument("--clean", action="store_true",
                    help="Delete existing apn_c22_all_*.m files in output directory before generating")
    ap.add_argument("--manifest", type=Path, default=None,
                    help="Manifest JSON path; default is seeds/c22_exhaustive_manifest.json")
    args = ap.parse_args()

    out_dir = args.out.resolve() if args.out else gb._DEFAULT_OUT_DIR
    manifest_path = args.manifest.resolve() if args.manifest else (gb._REPO_ROOT / "seeds" / "c22_exhaustive_manifest.json")

    rank, basis_param_indices = build_projection_basis()
    total = 1 << rank

    print("Class-22 exhaustive NL=4 slice generator")
    print(f"dim(V22)                 : {len(gb.fc22)}")
    print(f"fixed coordinates p<=4   : {len(gb.C22_FIXED_VARS)}")
    print(f"free coordinates p>4     : {len(gb.C22_FREE_VARS)}")
    print(f"projection rank          : {rank}")
    print(f"total distinct slices    : {total}")
    print(f"basis param indices      : {basis_param_indices}")

    if rank != 16:
        print("WARNING: projection rank is not 16. Check assumptions before large run.")

    if args.start < 0 or args.start >= total:
        raise ValueError(f"--start must be in [0,{total-1}]")
    if args.count < 1:
        raise ValueError("--count must be positive")

    end = min(args.start + args.count, total)

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "results").mkdir(exist_ok=True)

    if args.clean:
        for p in out_dir.glob("apn_c22_all_*.m"):
            p.unlink()

    written = []
    manifest_records = []

    for slice_idx in range(args.start, end):
        coeffs = coeffs_for_slice_index(slice_idx, basis_param_indices)

        # Use a large seed_idx only for labels inside Magma.
        label_idx = slice_idx + 1
        magma_text = gb.gen_class22_nl4(label_idx, coeffs)
        magma_text = patch_magma_text(magma_text)

        fname = out_dir / f"apn_c22_all_{slice_idx:05d}.m"
        gb.write_ascii(fname, magma_text)
        written.append(str(fname))

        manifest_records.append({
            "slice_index": slice_idx,
            "file": fname.name,
            "result_tag": f"c22_nl4_s{label_idx:02d}",
            "signature": gb.c22_signature(coeffs),
            "basis_param_indices": basis_param_indices,
            "coeffs": coeffs,
        })

    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    existing = {}
    if manifest_path.exists():
        try:
            existing = json.load(open(manifest_path, "r", encoding="utf-8"))
        except Exception:
            existing = {}

    old_records = existing.get("records", [])
    by_idx = {r["slice_index"]: r for r in old_records if "slice_index" in r}
    for r in manifest_records:
        by_idx[r["slice_index"]] = r

    manifest = {
        "updated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "generator": "gen_c22_exhaustive_slices.py",
        "class": "Class-22",
        "mode": "exhaustive_NL4_projection",
        "dim_V22": len(gb.fc22),
        "projection_rank": rank,
        "total_distinct_slices": total,
        "fixed_coordinates": len(gb.C22_FIXED_VARS),
        "free_coordinates": len(gb.C22_FREE_VARS),
        "basis_param_indices": basis_param_indices,
        "records": [by_idx[k] for k in sorted(by_idx)],
    }

    json.dump(manifest, open(manifest_path, "w", encoding="utf-8"), indent=2)

    print()
    print("SUMMARY")
    print("=" * 60)
    print(f"Generated slice indices : {args.start} .. {end-1}")
    print(f"Files written           : {len(written)}")
    print(f"Output directory        : {out_dir}")
    print(f"Manifest                : {manifest_path}")
    print()
    print("Next:")
    print(f"  cd {out_dir}")
    print('  powershell -ExecutionPolicy Bypass -File ..\\magma_templates\\run_batch.ps1 -Pattern "apn_c22_all_*.m"')


if __name__ == "__main__":
    main()
